# Generated by Django 3.1.10 on 2022-10-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_scan_address_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('country', models.TextField()),
                ('coords', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='port_info',
            name='score',
            field=models.FloatField(),
        ),
    ]
