# Generated by Django 3.1.10 on 2022-10-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20221018_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
