# Generated by Django 3.1.10 on 2022-10-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_device_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='shodan_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
            ],
        ),
    ]
